### ISSUE TITLE
weighted gradient applications

### ISSUE THREAD

**Issue by chaffra** [mikaem/fenicstools#14]
Hello,

I am trying to calculate a smooth gradient for my solution to a drift diffusion problem. Although the solution looks smooth when using CG1 elements the gradient has a lot of artificial spikes when projecting i.e .

`grad_u = project(grad(u))`

I was wondering if your weighted gradient methods could help. Could you please refer me to some references on applications for it or what it is used for?

The image below should show the spikes I am talking about.
Thanks,
Chaffra

![image](https://cloud.githubusercontent.com/assets/2158653/16200696/59d0632c-36dc-11e6-8570-e78b44fd0f6a.png)

**Comment by mikaem** [comment]
Hi
The weighted gradient method is used to compute a gradient field faster than project by avoiding a linear algebra solve. An example of usage is in https://github.com/mikaem/fenicstools/blob/master/demo/test_weight_grad.py
You might also want to look at Clement interpolation that can achieve the same thing.
