### ISSUE TITLE
Simple probe fails

### ISSUE THREAD

**Issue by jywuce** [mikaem/fenicstools#19]
I have the following simple code test.py for probe:
> from dolfin import *
> from numpy import array
> from fenicstools import *
> 
> mesh = UnitSquareMesh(10, 10)
> V = FunctionSpace(mesh, 'CG', 1)
> u = interpolate(Expression("sin(x[0]*pi)*cos(x[1]*pi)"), V)
> 
> x = array([0.6, 0.5])
> probe = Probe(x, V)
> probe(u)
> 
> print "result = ", probe.get_probe_sub(0)

It gives the correct result "0" (almost) if I run it in series: python test.py
However, when I run it in parallel: mpirun -np 2 python test.py, it seems that the probe fails.

> *** -------------------------------------------------------------------------
>*** DOLFIN encountered an error. If you are not able to resolve this issue
>*** using the information listed below, you can ask for help at
>***
>***     fenics-support@googlegroups.com
>***
>*** Remember to include the error message listed below and, if possible,
>*** include a *minimal* running example to reproduce the error.
>***
>*** -------------------------------------------------------------------------
>*** Error:   Unable to set probe.
>*** Reason:  Probe is not found on processor.
>*** Where:   This error was encountered inside Probe.cpp.
>*** Process: 0
>*** 
>*** DOLFIN version: 2016.1.0
>*** Git changeset:  
>*** -------------------------------------------------------------------------

Very interestingly, if I probe the array [0.5, 0.5], it does give the correct result.
Furthermore, I tried to use compute_first_entity_collision() directly in fenics, 
it also fails. I think it might be some bugs in fenics. Could you please confirm 
it or fix the bug? Thanks!

**Comment by MiroK** [comment]
Yes, I can reproduce this. The case [0.5, 0.5] most likely passes because the point lies on the boundary between CPUs. Anyways, I have no issues with `entity_collision`, in particular the following works as expected (i.e. only one CPU finds the point)

````python
from dolfin import *
from numpy import array
from fenicstools import *

mesh = UnitSquareMesh(10, 10)

x = array([0.6, 0.5])
p = Point(x)

tree = mesh.bounding_box_tree()
foo = tree.compute_first_collision(p) 
print foo
````

I would like the probe initialization to fail only if the probe is not found on any of the processes, how about it  @mikaem ?

**Comment by jywuce** [comment]
Yes, MiroK (the same on FEniCS Q&A?). Your codes works as expected. 
I also noticed that in your cpp code, you use tree.compute_first_collision() to probe the point, 
but it fails. So, where is the bug, in FEnics or FEnicsTools?

**Comment by mikaem** [comment]
Hi
The `Probe` is not supposed to work in parallel. You need to use `Probes`. `Probes` tries to evaluate a `Probe` on each process, and only when successful is a probe created locally. The error message you see is caught by [Probes.Probes()](https://github.com/mikaem/fenicstools/blob/master/fenicstools/Probe/Probes.cpp)

**Comment by jywuce** [comment]
Thanks, Mihaem. With the Probes(), now the code works.
Could you please tell me how to get the meaningful probed value?
I tried probes.array() as said in wiki, but it also gives "none" for those unprobed domain.

**Comment by jywuce** [comment]
Any one can help?

**Comment by mikaem** [comment]
If you only want to print on root, then you can do something like
    
    a = probes.array()
    if comm.Get_rank() == 0:
        print(a)

`probes.array` is a function called by all ranks, and all but root gets None as return type.
