### ISSUE TITLE
fencistools for fenics-2017.2

### ISSUE THREAD

**Issue by yuxianglin** [mikaem/fenicstools#30]
Hi, 

I am wondering if there is a compatible version for fenics 2017.2.0? I am running on a fencis 2017.2 and current mater branch seems works for 2018.1, other version I found works for 2017.1.0 and I tried but got unexpected error when swigging: error: conversion from ‘Eigen::Map<const Eigen::Array<int, -1, 1> >’ to non-scalar type ‘const dolfin::ArrayView<const int>’ requested
         = dofmap_u->cell_dofs(cell->index());

**Comment by mikaem** [comment]
Sorry, no version available for 2017.2
